import { istDateString } from "@/lib/utils/formatters";

/**
 * Developer's share: 10% of the profit generated by orders (item gross margin +
 * the shop's delivery share). This is an admin↔developer accounting item — it is
 * never charged to customers and only reduces reported net profit. Settlements
 * record a `settled_through` cutoff; outstanding share is computed over orders
 * created AFTER the latest settlement (falling back to DEV_FEE_START).
 */
export const DEV_FEE_RATE = 0.1;
export const DEV_FEE_START = "2026-06-10";
export const DEV_FEE_START_LABEL = "10 Jun, 2026";

export interface DevShareOrder {
  created_at: string;
  status?: string;
  subtotal: number | string;
  admin_delivery_earning: number | string;
  order_items: { quantity: number; cost_price: number | string | null }[];
}

/** Profit base contributed by one order (item margin + shop delivery share). */
export function orderDevBase(o: DevShareOrder): number {
  const itemsCost = o.order_items.reduce(
    (a, it) => a + it.quantity * Number(it.cost_price ?? 0),
    0
  );
  return Number(o.subtotal) - itemsCost + Number(o.admin_delivery_earning);
}

/**
 * Accrued developer share over the given orders. When `sinceIso` is provided
 * (the last settlement cutoff), only orders created strictly after it count;
 * otherwise everything from DEV_FEE_START onwards counts. Cancelled orders are
 * always excluded.
 */
export function computeDevShare(
  orders: DevShareOrder[],
  sinceIso?: string | null
): { base: number; share: number } {
  const base = orders.reduce((sum, o) => {
    if (o.status === "cancelled") return sum;
    if (sinceIso) {
      if (o.created_at <= sinceIso) return sum;
    } else if (istDateString(o.created_at) < DEV_FEE_START) {
      return sum;
    }
    return sum + orderDevBase(o);
  }, 0);
  return { base, share: base * DEV_FEE_RATE };
}
